# Generated by Django 5.2.6 on 2026-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('ADMIN', 'Admin'), ('PRO', 'Pro')], default='FREE', max_length=16),
        ),
    ]
