# Generated by Django 5.2.6 on 2025-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('company_name', models.CharField(max_length=255)),
                ('company_exchange', models.CharField(blank=True, max_length=64)),
                ('sector', models.CharField(blank=True, max_length=128)),
                ('metodo', models.CharField(choices=[('1', 'CAGR (compuesto)'), ('2', 'Promedio año a año')], max_length=2)),
                ('fuente_solicitada', models.CharField(blank=True, max_length=16)),
                ('fuente_utilizada', models.CharField(blank=True, max_length=16)),
                ('valor_intrinseco', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('diferencia_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('estado', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['ticker', 'created_at'], name='dcf_app_ana_ticker_869001_idx')],
            },
        ),
    ]
