# Generated by Django 5.2.6 on 2026-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_exchange', models.CharField(blank=True, max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('ticker',),
            },
        ),
    ]
