# Generated by Django 5.2.6 on 2026-05-24 16:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_items_to_general(apps, schema_editor):
    WatchlistItem = apps.get_model('dcf_app', 'WatchlistItem')
    WatchlistGroup = apps.get_model('dcf_app', 'WatchlistGroup')
    orphans = WatchlistItem.objects.filter(watchlist__isnull=True)
    if orphans.exists():
        general = WatchlistGroup.objects.create(name='General')
        orphans.update(watchlist=general)


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_app', '0002_watchlist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='ticker',
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dcf_app.watchlistgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'ticker')},
        ),
        migrations.RunPython(migrate_items_to_general, migrations.RunPython.noop),
    ]
