# Generated by Django 5.2.6 on 2026-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcf_app', '0004_analysisrecord_user_watchlistgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrecord',
            name='metodo',
            field=models.CharField(blank=True, choices=[('1', 'CAGR (compuesto)'), ('2', 'Promedio año a año')], max_length=2, null=True),
        ),
    ]
